version: 2

# Time is UTC

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
