version: 2

# Time is UTC

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "05:00"
    commit-message:
      prefix: chore(deps)
    ignore:
      # Dependabot fails to update Elixir and Erlang. They are updated manually.
      - dependency-name: hexpm/elixir
      - dependency-name: node
        update-types: [version-update:semver-major]

  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily
      time: "05:00"
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "05:00"
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
