# Labels for action/labeler

# —————————————————————————————————————————————— #
#                Labels by purpose               #
# —————————————————————————————————————————————— #

source:
  - any: ["**/lib/**/*", "!scripts/lib/**/*"]
  - "**/src/**/*"

tests:
  - "**/test/**/*"

dependencies:
  - "**/package*.json"
  - "**/mix.exs"
  - "**/mix.lock"

documentation:
  - docs/**/*
  - LICENSE
  - README.md
  - RELEASE.md

chore:
  - .browserslist*
  - .commitlint*
  - .cz.json
  - .devcontainer
  - .editorconfig
  - .eslint*
  - .hadolint*
  - .htmlhint*
  - .husky/**/*
  - .lintstaged*
  - .markdownlint*
  - .prettier*
  - .stylelint*
  - .vscode/**/*
  - "**/.check*.exs"
  - "**/.credo.exs"
  - "**/.dialyzer_ignore.exs"
  - "**/.formatter.exs"
  - "**/.gitignore"
  - "**/.gitkeep"
  - "**/.npmrc"
  - "**/.sobelow-conf"
  - codecov.yml
  - coveralls.json
  - cspell.yml
  - run
  - scripts/**/*
  - spellcheck/**/*

template:
  - "**/*.eex"
  - "**/*.leex"

# —————————————————————————————————————————————— #
#         Labels by technology / language        #
# —————————————————————————————————————————————— #

docker:
  - .dockerignore
  - docker-compose*.yml
  - Dockerfile*

elixir:
  - "**/*.ex"
  - "**/*.exs"
  - "**/*.eex"
  - "**/*.leex"
  - "**/.credo.exs"
  - "**/.formatter.exs"
  - "**/mix.exs"
  - "**/mix.lock"

github_actions:
  - .github/**/*

html:
  - "**/*.html*"

javascript:
  - "**/*.js"
  - "**/.npmrc"
  - "**/package*.json"

shellscript:
  - "**/*.sh"
  - .husky/*
  - run

vscode:
  - .vscode/**/*
