env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

reportUnusedDisableDirectives: true

# Order is important: top configs are overridden by bottom ones
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:array-func/recommended
  - plugin:compat/recommended
  - plugin:eslint-comments/recommended
  - plugin:import/recommended
  - plugin:no-use-extend-native/recommended
  - plugin:promise/recommended
  - plugin:regexp/recommended
  - plugin:unicorn/recommended
  - prettier # Must be last

rules: { no-warning-comments: warn }
