env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

reportUnusedDisableDirectives: true

plugins:
  - prefer-object-spread
  - switch-case

# Order is important: top configs are overridden by bottom ones
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:array-func/recommended
  - plugin:compat/recommended
  - plugin:eslint-comments/recommended
  - plugin:import/recommended
  - plugin:no-use-extend-native/recommended
  - plugin:promise/recommended
  - plugin:regexp/recommended
  - plugin:switch-case/recommended
  - plugin:unicorn/recommended
  - prettier # Must be last

rules: {
    # Core rules
    no-warning-comments: error,
    # Plugin rules
    import/no-extraneous-dependencies:
      [error, { devDependencies: [./scripts/**/*.js, .release-it.js] }],
    prefer-object-spread/prefer-object-spread: error,
    switch-case/newline-between-switch-case:
      [error, always, { fallthrough: never }],
  }

overrides:
  - files:
      - ./scripts/**/*.js
      - .release-it.js
    rules:
      unicorn/prefer-module: off
