# Order is important: top configs are overridden by bottom ones
extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-recommended-scss
  - stylelint-config-sass-guidelines
  - stylelint-config-idiomatic-order
  - "@ronilaukkarinen/stylelint-a11y/recommended"

plugins:
  - stylelint-at-rule-no-children
  - "@ronilaukkarinen/stylelint-a11y"
  - stylelint-csstree-validator
  - stylelint-color-format
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-declaration-strict-value
  - stylelint-high-performance-animation
  - stylelint-no-unsupported-browser-features
  - stylelint-use-logical-spec
  - stylelint-use-nesting

reportDescriptionlessDisables: true
reportInvalidScopeDisables: true
reportNeedlessDisables: true

rules:
  # Rules from core
  alpha-value-notation: number
  color-function-notation: modern
  color-no-hex: true
  font-family-name-quotes: always-unless-keyword
  font-weight-notation:
    - numeric
    - ignore:
        - relative
  function-url-no-scheme-relative: true
  hue-degree-notation: number
  selector-max-id: 0

  # Rules from plugins
  a11y/font-size-is-readable: true
  a11y/media-prefers-color-scheme: true
  a11y/no-obsolete-attribute: true
  a11y/no-obsolete-element: true
  a11y/no-text-align-justify: true
  color-format/format:
    format: hsl
  csstools/use-nesting: always
  csstree/validator:
    syntaxExtensions:
      - sass
  liberty/use-logical-spec: true
  order/properties-alphabetical-order: null
  plugin/declaration-block-no-ignored-properties: true
  plugin/no-low-performance-animation-properties: true
  plugin/no-unsupported-browser-features: true
  scale-unlimited/declaration-strict-value:
    - - /color/
      - fill
      - stroke
      - font-family
      - font-size
      - line-height
      - z-index
    - ignoreValues:
        /color/: &keywords [currentColor, inherit, transparent]
        fill: *keywords
        stroke: *keywords
      disableFix: true
