version: "3.9"

services:
  app:
    image: aifrak/template-elixir:latest
    build:
      context: .
      target: base
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

volumes:
  app-node-modules:
