#!/usr/bin/env bash

set -euo pipefail

if [[ -z "${APP_DIR:-""}" ]]; then
  APP_DIR="$(dirname "${0}")"
fi

. "${APP_DIR}/scripts/run/css.sh"
. "${APP_DIR}/scripts/run/docker-file.sh"
. "${APP_DIR}/scripts/run/elixir.sh"
. "${APP_DIR}/scripts/run/git.sh"
. "${APP_DIR}/scripts/run/html.sh"
. "${APP_DIR}/scripts/run/javascript.sh"
. "${APP_DIR}/scripts/run/markdown.sh"
. "${APP_DIR}/scripts/run/prettier.sh"
. "${APP_DIR}/scripts/run/shell.sh"
. "${APP_DIR}/scripts/run/spellcheck.sh"
. "${APP_DIR}/scripts/lib/utils.sh"

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

function help {
  cat <<EOF

$0 [command] [--dev] [sub-command]

Example: $0 --dev dc:exec ./run test

Options:
  -h, --help                  Print this message
  --dev                       Use "dev" file when docker compose

Main commands:
  help                        Print this message
  format                      Format code of the whole project
  install-deps                Install all dependencies
  lint                        Lint the whole project
  pre-commit                  Format, lint and test the whole project
  test                        Test the whole project

docker-compose commands:
  dc:build                    Build all docker services
  dc:console                  Build, start, up all services and console of "app" docker service
  dc:exec                     Execute a command in a "app" docker service
  dc:run                      Run a command inside the "app" docker service and remove stopped containers
  dc:up                       Starts all docker services
EOF

  elixir:help
  css:help
  html:help
  js:help
  markdown:help
  prettier:help
  shell:help
  dockerfile:help
  spellcheck:help
  git:help
}

# —————————————————————————————————————————————— #
#                Helper functions                #
# —————————————————————————————————————————————— #

# Check if the command is from the docker container or the host.
# INSIDE_DOCKER=1 is set from the Dockerfile
function is_inside_docker {
  if [[ ${INSIDE_DOCKER:-0} -eq 1 ]]; then
    return 0
  else
    return 1
  fi
}

function is_ci {
  if [[ "${CI:-false}" = true ]]; then
    return 0
  else
    return 1
  fi
}

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
# Idea from: https://github.com/nickjj/docker-flask-example/blob/main/run
TTY=""
if [[ ! -t 1 ]] || is_ci; then
  TTY="-T"
fi

# —————————————————————————————————————————————— #
#                   Application                  #
# —————————————————————————————————————————————— #

function test {
  if is_inside_docker; then
    mix check --only ex_unit
  else
    dc:exec ./run test
  fi
}

function lint {
  # shellcheck disable=SC2119
  if is_inside_docker; then
    mix check --except ex_unit
  else
    dc:exec ./run lint
  fi
}

function format {
  # shellcheck disable=SC2119
  if is_inside_docker; then
    mix format.all
  else
    dc:exec ./run format
  fi
}

function pre-commit {
  if is_inside_docker; then
    format
    mix check
  else
    dc:exec ./run pre-commit
  fi
}

function install-deps {
  if is_inside_docker; then
    mix setup.dev
  else
    dc:exec ./run install-deps
  fi
}

# —————————————————————————————————————————————— #
#                 docker-compose                 #
# —————————————————————————————————————————————— #

dc_options=()

dev_dc_options=(
  -f docker-compose.yml
  -f docker-compose.dev.yml
)

function dc {
  docker-compose "${dc_options[@]}" "${@}"
}

function dc:build {
  docker buildx bake "${dc_options[@]}"
}

function dc:exec {
  dc exec ${TTY} app "${@}"
}

function dc:run {
  dc run ${TTY} app "${@}"
  dc rm -f -v
}

function dc:up {
  dc up -d --remove-orphans
}

function dc:console {
  dc:build
  dc:up
  dc:exec bash
}

# —————————————————————————————————————————————— #
#                       run                      #
# —————————————————————————————————————————————— #

for opt in "${@}"; do
  case ${opt} in
    --dev)
      dc_options=("${dev_dc_options[@]}")
      shift
      ;;
    -h | --help)
      help
      close
      ;;
  esac
done

# Idea from: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
