#!/usr/bin/env sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

commit_message_path="$1"

npx commitlint --color --edit "$commit_message_path"
npx cspell lint --color "$commit_message_path"
