#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

commit_message_path="$1"

npx --no-install commitlint --color --edit "$commit_message_path"
npx --no-install cspell lint --color "$commit_message_path"
