#!/usr/bin/env sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

if [ "${CI:-false}" = false ] && [ -n "$INSIDE_DOCKER" ]; then
  echo "Git Hook triggered: 'post-checkout'"

  diff=$(git diff --name-only "$1" "$2")

  run_cmd_when_changed_files "package-lock.json" "npm ci" "$diff"
fi
