#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

if [ -n "$RELEASE" ]; then
  ./run lint-staged
elif [ -n "$INSIDE_DOCKER" ]; then
  ./run pre-commit
else
  ./run --dc-dev dc:build
  ./run --dc-dev dc:up
  ./run --dc-dev dc:exec ./run install-deps
  ./run --dc-dev dc:exec ./run pre-commit
fi
