#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

if [ -n "$RELEASE" ]; then
  npx lint-staged
elif [ -n "$INSIDE_DOCKER" ]; then
  npx lint-staged
  mix check --only ex_unit
else
  ./run --dc-dev dc:build
  ./run --dc-dev dc:up
  ./run --dc-dev dc:exec ./run install-deps
  ./run --dc-dev dc:exec npx lint-staged
  ./run --dc-dev dc:exec mix check --only ex_unit
fi
