name: Audit npm packages

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "**/package.json"
      - "**/package-lock.json"
  schedule:
    - cron: "30 5 * * 1-5"

jobs:
  npm-audit:
    name: Audit npm packages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Audit packages
        run: npm audit
