name: Dependabot auto merge

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot auto merge
        uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
