name: Dependabot auto merge

# Check Dependabot PRs every weekday at 06:30 UTC (after Dependabot)
on:
  schedule:
    - cron: "30 6 * * 1-5"

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - name: Dependabot auto merge
        uses: PabioHQ/dependabot-pr-action@v1.1.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-label: true
          approve: true
          merge-minor: true
          merge-patch: true
          merge-preminor: true
          merge-prepatch: true
