name: Update license year

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 UTC on the 1st in Jan.
    - cron: "0 3 1 1 *"

jobs:
  update-license:
    name: Update license year
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.1

      - name: Update license year
        uses: FantasticFiasco/action-update-license-year@v2.2.1
        with:
          token: ${{ secrets.PAT_GITHUB }}
          prTitle: "docs(license): Update copyright year to {{currentYear}}"
          commitTitle: "docs(license): Update copyright year to {{currentYear}}"
