name: Update license year

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 UTC on the 1st in Jan.
    - cron: "0 3 1 1 *"

jobs:
  update-license:
    name: Update license year
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Update license year
        uses: FantasticFiasco/action-update-license-year@51f54700fd5cc2955c951454149d9bfb72d7716a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commitTitle: "docs(license): Update copyright year to {{currentYear}}"
